server:
  port: 8080

spring:
  datasource:
    username: root
    password: '@mecomeon'
    url: jdbc:mysql://localhost:3306/conference_system

  redis:
    port: 6379
    host: localhost

logging:
  level:
    com.example: debug

